--==============================================================================
-- DBMS Name        :    SQL Server
-- Procedure Name   :    UPDATE_STAGE_ADDRESS_copy
-- Template         :    wsl_sqlserver_proc_stage
-- Template Version :    8.1.1.0
-- Description      :    Update the Stage Table table STAGE_ADDRESS_copy
-- Generated by     :    WhereScape RED Version 10.4.0.3 (build 250520-210950)
-- Generated for    :    Employee Sultan Shiffa
-- Generated on     :    Monday, August 11, 2025 at 11:19:45
-- Author           :    demo
--==============================================================================
-- Notes / History
--
CREATE PROCEDURE [SCHEMA.UPDATE_STAGE_ADDRESS_copy].UPDATE_STAGE_ADDRESS_copy
  @p_sequence         INTEGER
, @p_job_name         VARCHAR(256)
, @p_task_name        VARCHAR(256)
, @p_job_id           INTEGER
, @p_task_id          INTEGER
, @p_return_msg       VARCHAR(1024) OUTPUT
, @p_status           INTEGER       OUTPUT

AS
  SET XACT_ABORT OFF  -- Turn off auto abort on errors
  SET NOCOUNT ON      -- Turn off row count messages

  --=====================================================
  -- Control variables used in most programs
  --=====================================================
  DECLARE
    @v_msgtext               VARCHAR(1024) -- Text for audit_trail
  , @v_sql                   NVARCHAR(255) -- Text for SQL statements
  , @v_step                  INTEGER       -- return code
  , @v_merged_count          INTEGER       -- no of records merged
  , @v_insert_count          INTEGER       -- no of records inserted
  , @v_update_count          INTEGER       -- no of records updated
  , @v_dim_insert_count      INTEGER       -- no of records inserted to Dimension
  , @v_return_status         INTEGER       -- Update result status
  , @v_current_datetime      DATETIME      -- Used for date insert

  --=====================================================
  -- General Variables
  --=====================================================




  --=====================================================
  -- MAIN
  --=====================================================
  SET @v_step = 100

  SET @v_insert_count = 0
  SET @v_update_count = 0
  SET @v_dim_insert_count = 0
  SET @v_current_datetime = GETDATE()

  BEGIN TRY

    --=====================================================
    -- Delete existing records
    --=====================================================
    SET @v_step = 200

    SET @v_sql = N'TRUNCATE TABLE [TABLEOWNER].[STAGE_ADDRESS_copy]';
    EXEC @v_return_status = sp_executesql @v_sql



    --=====================================================
    -- Insert new records
    --=====================================================
    SET @v_step = 300

    BEGIN TRANSACTION

      INSERT INTO [TABLEOWNER].[STAGE_ADDRESS_copy]
     (  ADDRESS_ID
        , ADDRESS_TYPE_CODE
      ) 
      SELECT  count(LOAD_ADDRESS.ADDRESS_ID) AS ADDRESS_ID
           , LOAD_ADDRESS.ADDRESS_TYPE_CODE AS ADDRESS_TYPE_CODE
      FROM [TABLEOWNER].[LOAD_ADDRESS] LOAD_ADDRESS
      GROUP BY LOAD_ADDRESS.ADDRESS_TYPE_CODE
      ;

      SELECT @v_insert_count = @@ROWCOUNT
    COMMIT


    --=====================================================
    -- All Done report the results
    --=====================================================
    SET @v_step = 400

    SET @p_status = 1
    SET @p_return_msg = 'STAGE_ADDRESS_copy updated. '
      + CONVERT(VARCHAR,@v_insert_count) + ' records inserted.'
      + CONVERT(VARCHAR,@v_update_count) + ' records updated.'


    RETURN 0


  END TRY
  BEGIN CATCH

    SET @p_status = -2
    SET @p_return_msg = SUBSTRING('UPDATE_STAGE_ADDRESS_copy FAILED with error '
      + CONVERT(VARCHAR,ISNULL(ERROR_NUMBER(),0))
      + ' Step ' + CONVERT(VARCHAR,ISNULL(@v_step,0))
      + '. Error Msg: ' + ERROR_MESSAGE(),1,1023)

  END CATCH
  IF XACT_STATE() <> 0
  BEGIN
    ROLLBACK TRANSACTION
  END

  RETURN 0
